[[pages]]
path = "home.py"
name = "Home"

[[pages]]
path = "pages/videos.py"
name = "Videos"
icon = "ğŸ¬"

[[pages]]
path = "pages/images.py"
name = "Images"
icon = "ğŸï¸"

[[pages]]
path = "pages/audio.py"
name = "Audio"
icon = "ğŸ§"

[[pages]]
path = "pages/architecture.py"
name = "Tech Specs"
icon = "ğŸªœ"
